// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK4Ec5omm05BM2QWRWeNw87CYOyIlVOFw',
    appId: '1:1047072019183:web:53288b87841ae78e7c411a',
    messagingSenderId: '1047072019183',
    projectId: 'cards-against-humanity-demo',
    authDomain: 'cards-against-humanity-demo.firebaseapp.com',
    databaseURL: 'https://cards-against-humanity-demo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cards-against-humanity-demo.firebasestorage.app',
    measurementId: 'G-80GD1C83K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPukdO4MJIcMdA5UrWRybhOqUu1z1hFs',
    appId: '1:1047072019183:android:14a087b9a8aa4ad27c411a',
    messagingSenderId: '1047072019183',
    projectId: 'cards-against-humanity-demo',
    databaseURL: 'https://cards-against-humanity-demo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cards-against-humanity-demo.firebasestorage.app',
  );

}